global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus system metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - host system metrics (CPU, memory)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']